# Generated by Django 5.2.8 on 2025-11-24 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('smartphone', 'Smartphone'), ('notebook', 'Notebook'), ('smart_tv', 'Smart TV'), ('outro', 'Outro')], max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('tensao', models.CharField(blank=True, max_length=20)),
                ('dimensoes', models.CharField(blank=True, max_length=100)),
                ('resolucao_tela', models.CharField(blank=True, max_length=50)),
                ('capacidade_armazenamento', models.CharField(blank=True, max_length=50)),
                ('conectividade', models.CharField(blank=True, max_length=100)),
                ('quantidade_atual', models.IntegerField(default=0)),
                ('estoque_minimo', models.IntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('quantidade', models.IntegerField()),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.produto')),
            ],
        ),
    ]
